export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";

export const GET_SUPPLIERS = "GET_SUPPLIERS";
export const DELETE_SUPPLIERS = "DELETE_SUPPLIERS";
export const ADD_SUPPLIERS = "ADD_SUPPLIERS";

// PurchaseOrders
export const GET_PURCHASEORDERS = "GET_PURCHASEORDERS";
export const DELETE_PURCHASEORDER = "DELETE_PURCHASEORDER";
